// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itccifelwqwuhzcthmqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0Y2NpZmVsd3F3dWh6Y3RobXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MjcwNjIsImV4cCI6MjA1ODIwMzA2Mn0.xi3aUwKXP5fMM_RvnRp2_DZ-CzERGoUlDAiDjU19tAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);